# Generated by Django 5.1.5 on 2025-03-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
